version: '2.2'

networks:
    default:
        name: network
        driver: bridge

services:
  database:
    container_name: database
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=craft_ai
    ports:
      - 5432:5432

  api:
    container_name: api
    build: 
      context: ./back/api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=craft_ai
    volumes:
      - ./back/api:/usr/src/app
      - /usr/src/app/node_modules/

  processor:
    container_name: processor
    build: 
      context: ./back/processor
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - FACTORIZATION_API_HOST=http://api:3001
    volumes:
      - ./back/processor:/usr/src/app
      - /usr/src/app/node_modules/

  front:
    container_name: front
    build: 
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - NODE_ENV=development
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules/
